/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/waterfall.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.275, 47.443, -64.997]}
        rotation={[0, -0.026, 0]}
        scale={32.967}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials.ziemia}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_2.geometry}
          material={materials.trawa}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.water.geometry}
        material={materials.Water}
        position={[0.138, 51.857, -53.589]}
        rotation={[0, -0.026, 0]}
        scale={[16.355, 22.824, 31.278]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.water001.geometry}
        material={materials.Water}
        position={[54.321, 51.857, -48.206]}
        rotation={[0, -0.172, 0]}
        scale={[16.355, 22.824, 31.278]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.water002.geometry}
        material={materials.Water}
        position={[-51.794, 51.857, -46.79]}
        rotation={[0, 0.201, 0]}
        scale={[16.355, 22.824, 31.278]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.water003.geometry}
        material={materials.Water}
        position={[0, 3.401, -30.019]}
        scale={[94.907, 94.907, 76.602]}
      />
      <group position={[3.765, 5.051, -55.785]} rotation={[0, 0, 0.126]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials.tree}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_2.geometry}
          material={materials["stal mat"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_3.geometry}
          material={materials["zloto mat"]}
        />
      </group>
      <group
        position={[0.175, 2.327, 17.809]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-4.589, -0.421, -4.589]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.ziemia}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials.trawa}
        />
      </group>
      <group
        position={[0.175, 2.327, 17.809]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-4.589, -0.421, -4.589]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.ziemia}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials.trawa}
        />
      </group>
      <group position={[0.175, 5.169, 17.809]} scale={0.22}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004.geometry}
          material={materials.stal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004_1.geometry}
          material={materials.rekojesc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004_2.geometry}
          material={materials.skala}
        />
      </group>
      <group position={[-10.118, 32.036, 0.717]} scale={3.275}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_1.geometry}
          material={materials.skala}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_2.geometry}
          material={materials.trawa}
        />
      </group>
      <group position={[-10.118, 32.036, -9.658]} scale={3.275}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_1.geometry}
          material={materials.skala}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_2.geometry}
          material={materials.trawa}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.skala}
        position={[17.725, 4.872, 7.33]}
        rotation={[-0.582, -0.07, 2.662]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials.skala}
        position={[7.388, 3.617, 10.863]}
        rotation={[-0.43, -0.227, -2.648]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials.skala}
        position={[11.257, 3.605, 28.562]}
        rotation={[-0.582, -0.07, 2.662]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.skala}
        position={[-13.464, 4.083, 19.916]}
        rotation={[2.87, -0.528, -0.463]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials.skala}
        position={[-9.517, 3.617, 16.023]}
        rotation={[-0.43, -0.227, -2.648]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials.skala}
        position={[-16.215, 3.605, 32.116]}
        rotation={[-0.582, -0.07, 2.662]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials.skala}
        position={[-17.724, 3.605, 13.355]}
        rotation={[-1.715, -0.983, 0.965]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials.skala}
        position={[-3.528, 3.385, 9.896]}
        rotation={[0.944, -0.227, -2.648]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials.skala}
        position={[15.979, 3.617, 32.59]}
        rotation={[-0.43, -0.227, -2.648]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere012.geometry}
        material={materials.skala}
        position={[-6.871, 10.601, 8.817]}
        rotation={[2.465, 0.106, 1.854]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere013.geometry}
        material={materials.skala}
        position={[-0.153, 5.994, 2.638]}
        rotation={[1.757, -0.566, 0.479]}
        scale={9.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere014.geometry}
        material={materials.skala}
        position={[9.423, 7.537, 2.575]}
        rotation={[-2.778, -0.132, -2.532]}
        scale={7.384}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere015.geometry}
        material={materials.skala}
        position={[-11.496, 6.867, 4.205]}
        rotation={[-1.113, -0.132, -2.532]}
        scale={6.482}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials.skala}
        position={[13.815, 12.176, -55.903]}
        rotation={[1.129, -0.721, 0.81]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials.skala}
        position={[13.815, 8.986, -55.903]}
        rotation={[0.728, 0.28, 1.096]}
        scale={[0.969, 0.709, 0.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials.skala}
        position={[11.737, 11.424, -60.455]}
        rotation={[-1.335, 0.28, 1.096]}
        scale={[1.328, 0.971, 0.904]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials.skala}
        position={[-8.873, 12.176, -58.652]}
        rotation={[2.361, -0.266, 2.748]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials.skala}
        position={[-8.129, 8.986, -60.133]}
        rotation={[1.249, -0.831, 2.485]}
        scale={[0.969, 0.709, 0.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials.skala}
        position={[-3.415, 11.424, -61.81]}
        rotation={[-1.304, -0.25, -0.494]}
        scale={[1.328, 0.971, 0.904]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane115.geometry}
        material={materials.tree}
        position={[6.685, 4.573, 23.489]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[4.207, 4.719, 25.055]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane117.geometry}
        material={materials.tree}
        position={[4.202, 4.573, 25.047]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[6.954, 4.719, 19.35]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <group
        position={[6.69, 4.719, 23.497]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane120.geometry}
        material={materials.tree}
        position={[6.949, 4.573, 19.341]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[13.136, 4.719, 22.678]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane122.geometry}
        material={materials.tree}
        position={[13.13, 4.573, 22.67]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[17.204, 4.719, 27.406]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane124.geometry}
        material={materials.tree}
        position={[17.198, 4.573, 27.398]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[11.63, 4.719, 26.72]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane126.geometry}
        material={materials.tree}
        position={[11.625, 4.573, 26.711]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[3.105, 4.719, 33.59]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane128.geometry}
        material={materials.tree}
        position={[2.97, 4.573, 33.284]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-6.063, 4.719, 32.142]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane130.geometry}
        material={materials.tree}
        position={[-6.068, 4.573, 32.134]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-1.68, 4.719, 29.177]}
        rotation={[-2.447, -1.394, -2.401]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane132.geometry}
        material={materials.tree}
        position={[-1.686, 4.573, 29.184]}
        rotation={[0, 0.309, -0.125]}
        scale={0.441}
      />
      <group
        position={[-14.388, 4.719, 25.788]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane134.geometry}
        material={materials.tree}
        position={[-14.394, 4.573, 25.78]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-9.952, 4.719, 31.704]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane136.geometry}
        material={materials.tree}
        position={[-9.957, 4.573, 31.696]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[1.382, 4.719, 37.018]}
        rotation={[-2.268, 1.424, 2.327]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane138.geometry}
        material={materials.tree}
        position={[1.387, 4.573, 37.009]}
        rotation={[-Math.PI, -0.54, 3.017]}
        scale={0.441}
      />
      <group
        position={[10.096, 4.719, 33.238]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane140.geometry}
        material={materials.tree}
        position={[10.091, 4.573, 33.23]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-5.46, 4.719, 18.229]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane142.geometry}
        material={materials.tree}
        position={[-5.465, 4.573, 18.221]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[8.398, 4.719, 15.765]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane144.geometry}
        material={materials.tree}
        position={[8.393, 4.573, 15.756]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-1.023, 4.719, 13.464]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane146.geometry}
        material={materials.tree}
        position={[-1.028, 4.573, 13.456]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[19.956, 4.719, 21.845]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane148.geometry}
        material={materials.tree}
        position={[19.951, 4.573, 21.836]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[10.26, 4.719, 20.859]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane150.geometry}
        material={materials.tree}
        position={[10.255, 4.573, 20.85]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[8.343, 4.719, 30.718]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane152.geometry}
        material={materials.tree}
        position={[8.338, 4.573, 30.71]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-5.022, 4.719, 36.853]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane154.geometry}
        material={materials.tree}
        position={[-5.027, 4.573, 36.845]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-18.77, 4.719, 25.624]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane156.geometry}
        material={materials.tree}
        position={[-18.776, 4.573, 25.616]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-14.662, 4.719, 29.349]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane158.geometry}
        material={materials.tree}
        position={[-14.668, 4.573, 29.341]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-7.322, 4.719, 26.72]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane160.geometry}
        material={materials.tree}
        position={[-7.328, 4.573, 26.711]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <group
        position={[-5.843, 4.719, 15.436]}
        rotation={[-3.019, 0.404, -3.136]}
        scale={[0.333, 0.333, 0.158]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.bialy}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane162.geometry}
        material={materials.tree}
        position={[-5.849, 4.573, 15.428]}
        rotation={[0, -1.532, -0.125]}
        scale={0.441}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane163.geometry}
        material={materials["wystajaca trawa"]}
        position={[1.669, 4.56, 38.366]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane164.geometry}
        material={materials["wystajaca trawa"]}
        position={[3.634, 4.56, 36.718]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane165.geometry}
        material={materials["wystajaca trawa"]}
        position={[-0.53, 4.56, 36.718]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane166.geometry}
        material={materials["wystajaca trawa"]}
        position={[4.691, 4.56, 38.304]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane167.geometry}
        material={materials["wystajaca trawa"]}
        position={[-1.363, 4.56, 38.402]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane168.geometry}
        material={materials["wystajaca trawa"]}
        position={[-4.39, 4.56, 38.438]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane169.geometry}
        material={materials["wystajaca trawa"]}
        position={[-3.324, 4.56, 35.5]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane170.geometry}
        material={materials["wystajaca trawa"]}
        position={[-6.396, 4.56, 35.554]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane171.geometry}
        material={materials["wystajaca trawa"]}
        position={[-3.443, 4.56, 37]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane172.geometry}
        material={materials["wystajaca trawa"]}
        position={[-6.6, 4.56, 37]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane173.geometry}
        material={materials["wystajaca trawa"]}
        position={[-6.81, 4.56, 38.227]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane174.geometry}
        material={materials["wystajaca trawa"]}
        position={[-9.516, 4.56, 35.554]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane175.geometry}
        material={materials["wystajaca trawa"]}
        position={[-8.741, 4.56, 37.038]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane176.geometry}
        material={materials["wystajaca trawa"]}
        position={[-0.069, 4.56, 35.072]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane177.geometry}
        material={materials["wystajaca trawa"]}
        position={[2.953, 4.56, 35.009]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane178.geometry}
        material={materials["wystajaca trawa"]}
        position={[-0.069, 4.56, 35.072]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane179.geometry}
        material={materials["wystajaca trawa"]}
        position={[6.785, 4.56, 36.613]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane180.geometry}
        material={materials["wystajaca trawa"]}
        position={[-5.997, 4.56, 33.869]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane181.geometry}
        material={materials["wystajaca trawa"]}
        position={[-2.975, 4.56, 33.806]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane182.geometry}
        material={materials["wystajaca trawa"]}
        position={[-12.125, 4.56, 33.913]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane183.geometry}
        material={materials["wystajaca trawa"]}
        position={[-9.103, 4.56, 33.85]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane184.geometry}
        material={materials["wystajaca trawa"]}
        position={[-3.804, 4.56, 31.94]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane185.geometry}
        material={materials["wystajaca trawa"]}
        position={[-0.61, 4.56, 31.856]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane186.geometry}
        material={materials["wystajaca trawa"]}
        position={[0.992, 4.56, 33.449]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane187.geometry}
        material={materials["wystajaca trawa"]}
        position={[6.932, 4.56, 38.054]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane188.geometry}
        material={materials["wystajaca trawa"]}
        position={[6.063, 4.56, 35.04]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane189.geometry}
        material={materials["wystajaca trawa"]}
        position={[9.195, 4.56, 34.932]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane190.geometry}
        material={materials["wystajaca trawa"]}
        position={[5.359, 4.56, 33.311]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane191.geometry}
        material={materials["wystajaca trawa"]}
        position={[2.51, 4.56, 31.857]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane192.geometry}
        material={materials["wystajaca trawa"]}
        position={[5.667, 4.56, 31.671]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane193.geometry}
        material={materials["wystajaca trawa"]}
        position={[8.694, 4.56, 32.024]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane194.geometry}
        material={materials["wystajaca trawa"]}
        position={[8.269, 4.56, 33.467]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane195.geometry}
        material={materials["wystajaca trawa"]}
        position={[-4.776, 4.56, 28.036]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane196.geometry}
        material={materials["wystajaca trawa"]}
        position={[-4.485, 4.56, 30.146]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane197.geometry}
        material={materials["wystajaca trawa"]}
        position={[-4.693, 4.56, 25.995]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane198.geometry}
        material={materials["wystajaca trawa"]}
        position={[-1.393, 4.56, 27.86]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane199.geometry}
        material={materials["wystajaca trawa"]}
        position={[-1.582, 4.56, 26.026]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane200.geometry}
        material={materials["wystajaca trawa"]}
        position={[-11.211, 4.56, 29.991]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane201.geometry}
        material={materials["wystajaca trawa"]}
        position={[-12.689, 4.56, 31.725]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane202.geometry}
        material={materials["wystajaca trawa"]}
        position={[-12.104, 4.56, 28.11]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane203.geometry}
        material={materials["wystajaca trawa"]}
        position={[-8.06, 4.56, 29.885]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane204.geometry}
        material={materials["wystajaca trawa"]}
        position={[-8.339, 4.56, 28.151]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane205.geometry}
        material={materials["wystajaca trawa"]}
        position={[0.985, 4.56, 29.745]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane206.geometry}
        material={materials["wystajaca trawa"]}
        position={[-9.12, 4.56, 26.009]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane207.geometry}
        material={materials["wystajaca trawa"]}
        position={[-12.192, 4.56, 26.063]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane208.geometry}
        material={materials["wystajaca trawa"]}
        position={[-11.793, 4.56, 24.378]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane209.geometry}
        material={materials["wystajaca trawa"]}
        position={[-8.771, 4.56, 24.315]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane210.geometry}
        material={materials["wystajaca trawa"]}
        position={[-2.216, 4.56, 23.593]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane211.geometry}
        material={materials["wystajaca trawa"]}
        position={[-5.288, 4.56, 23.647]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane212.geometry}
        material={materials["wystajaca trawa"]}
        position={[-4.889, 4.56, 21.961]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane213.geometry}
        material={materials["wystajaca trawa"]}
        position={[-1.867, 4.56, 21.899]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane214.geometry}
        material={materials["wystajaca trawa"]}
        position={[-8.29, 4.56, 22.047]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane215.geometry}
        material={materials["wystajaca trawa"]}
        position={[-11.362, 4.56, 22.101]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane216.geometry}
        material={materials["wystajaca trawa"]}
        position={[-10.963, 4.56, 20.416]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane217.geometry}
        material={materials["wystajaca trawa"]}
        position={[-7.94, 4.56, 20.353]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane218.geometry}
        material={materials["wystajaca trawa"]}
        position={[4.224, 4.56, 23.28]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane219.geometry}
        material={materials["wystajaca trawa"]}
        position={[1.152, 4.56, 23.333]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane220.geometry}
        material={materials["wystajaca trawa"]}
        position={[1.551, 4.56, 21.648]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane221.geometry}
        material={materials["wystajaca trawa"]}
        position={[4.573, 4.56, 21.585]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane222.geometry}
        material={materials["wystajaca trawa"]}
        position={[7.081, 4.56, 28.342]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane223.geometry}
        material={materials["wystajaca trawa"]}
        position={[4.009, 4.56, 28.396]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane224.geometry}
        material={materials["wystajaca trawa"]}
        position={[4.408, 4.56, 26.71]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane225.geometry}
        material={materials["wystajaca trawa"]}
        position={[7.43, 4.56, 26.647]}
        rotation={[1.42, 0, 0]}
        scale={0.182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials.trawa}
        position={[10.927, 19.338, 14.026]}
        rotation={[0.209, 0.691, 2.584]}
        scale={[4.082, 3.032, 3.955]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials.trawa}
        position={[-10.771, 21.415, 19.894]}
        rotation={[2.978, -0.21, -0.458]}
        scale={[4.64, 3.446, 4.496]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pien002.geometry}
        material={materials.Tree}
        position={[12.911, 8.005, 13.96]}
        rotation={[0, -0.509, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pien003.geometry}
        material={materials.Tree}
        position={[-13.297, 8.532, 18.902]}
        rotation={[-Math.PI, 0.998, -Math.PI]}
        scale={1.137}
      />
      <group
        position={[-83.914, 80.497, -83.108]}
        scale={[4.292, 2.878, 4.292]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-85.496, 78.836, -44.922]}
        rotation={[0.143, 0, 0]}
        scale={[3.926, 2.632, 3.926]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-90.865, 78.635, -50.303]}
        rotation={[0, 0, -0.013]}
        scale={[2.748, 1.843, 2.748]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-78.543, 79.336, -54.028]}
        scale={[4.292, 2.878, 4.292]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-85.876, 79.857, -70.183]}
        scale={[4.008, 2.687, 4.008]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[-75.127, 78.899, -65.043]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-87.945, 77.942, -60.581]}
        scale={[1.784, 1.196, 1.784]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-23.405, 80.966, -95.651]}
        scale={[4.292, 2.878, 4.292]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-30.967, 79.316, -66.365]}
        scale={[4.292, 2.878, 4.292]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[23.939, 78.836, -58.222]}
        rotation={[0.143, 0, 0]}
        scale={[3.926, 2.632, 3.926]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-35.258, 78.889, -82.693]}
        rotation={[0, 0, -0.013]}
        scale={[2.748, 1.843, 2.748]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-34.949, 80.047, -92.915]}
        scale={[4.008, 2.687, 4.008]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[-19.833, 78.281, -81.942]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[-27.8, 77.843, -76.698]} scale={[1.784, 1.196, 1.784]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-30.251, 77.382, -55.467]}
        rotation={[0, 0, -0.013]}
        scale={[2.748, 1.843, 2.748]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group
        position={[-19.194, 76.653, -60.425]}
        scale={[1.784, 1.196, 1.784]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[25.207, 80.3, -94.844]} scale={[4.292, 2.878, 4.292]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[38.063, 78.899, -83.82]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[20.851, 78.607, -79.282]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[35.742, 79.851, -69.363]} scale={[4.292, 2.878, 4.292]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[36.505, 76.45, -55.044]} scale={[1.784, 1.196, 1.784]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[21.959, 77.916, -70.439]} scale={[1.784, 1.196, 1.784]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[78.929, 79.582, -52.307]} scale={[4.292, 2.878, 4.292]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[89.399, 78.445, -87.182]} scale={[1.784, 1.196, 1.784]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[80.311, 79.064, -83.663]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[88.604, 79.041, -71.928]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[79.242, 79.979, -67.642]} scale={[4.292, 2.878, 4.292]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[82.984, 78.316, -59.642]} scale={[1.784, 1.196, 1.784]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[90.169, 78.989, -55.811]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group position={[89.386, 78.217, -45.483]} scale={[2.968, 1.99, 2.968]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tree}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere016.geometry}
        material={materials.skala}
        position={[24.659, 37.304, -36.379]}
        rotation={[-2.021, 0.117, 1.83]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere017.geometry}
        material={materials.skala}
        position={[27.591, 39.628, -37.423]}
        rotation={[0.417, -0.915, -2.027]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere018.geometry}
        material={materials.skala}
        position={[32.726, 31.409, -35.583]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere019.geometry}
        material={materials.skala}
        position={[82.564, 66.625, -39.796]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere020.geometry}
        material={materials.skala}
        position={[71.74, 10.406, -28.962]}
        rotation={[0.417, -0.915, -2.027]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere021.geometry}
        material={materials.skala}
        position={[82.564, 46.662, -29.486]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere022.geometry}
        material={materials.skala}
        position={[-29.339, 37.304, -35.272]}
        rotation={[1.516, -1.242, -1.15]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere023.geometry}
        material={materials.skala}
        position={[-19.617, 53.383, -36.958]}
        rotation={[0.417, -0.915, -2.027]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere024.geometry}
        material={materials.skala}
        position={[-12.861, 20.463, -35.432]}
        rotation={[-0.278, 0.08, 1.846]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere025.geometry}
        material={materials.skala}
        position={[82.564, 66.625, -38.253]}
        rotation={[0.874, 0.609, 1.34]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere026.geometry}
        material={materials.skala}
        position={[79.884, 71.19, -48.567]}
        rotation={[-1.94, 0.609, 1.34]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere027.geometry}
        material={materials.skala}
        position={[90.471, 71.19, -68.986]}
        rotation={[-1.94, 0.609, 1.34]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere028.geometry}
        material={materials.skala}
        position={[87.801, 72.367, -77.895]}
        rotation={[-1.995, 0.265, -2.726]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere029.geometry}
        material={materials.skala}
        position={[89.471, 68.278, -46.015]}
        rotation={[-1.94, 0.609, 1.34]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere030.geometry}
        material={materials.skala}
        position={[-86.002, 32.327, -58.977]}
        rotation={[1.757, -0.566, 0.479]}
        scale={9.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere031.geometry}
        material={materials.skala}
        position={[-76.268, 63.329, -40.59]}
        rotation={[0.204, 1.01, 0.61]}
        scale={9.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere032.geometry}
        material={materials.skala}
        position={[-83.956, 51.819, -29.242]}
        rotation={[-2.778, -0.132, -2.532]}
        scale={7.384}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere033.geometry}
        material={materials.skala}
        position={[-68.013, 27.075, -30.075]}
        rotation={[1.003, -0.249, 1.08]}
        scale={7.384}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere034.geometry}
        material={materials.skala}
        position={[-29.138, 71.876, -87.576]}
        rotation={[-1.113, -0.132, -2.532]}
        scale={6.482}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere035.geometry}
        material={materials.skala}
        position={[-23.64, 67.098, -54.392]}
        rotation={[-2.394, -0.721, -1.102]}
        scale={6.482}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere036.geometry}
        material={materials.skala}
        position={[32.726, 53.307, -39.579]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere037.geometry}
        material={materials.skala}
        position={[27.756, 74.539, -82.86]}
        rotation={[-2.78, 1.431, -0.401]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere038.geometry}
        material={materials.skala}
        position={[29.658, 70.605, -58.535]}
        rotation={[-0.38, 1.194, 3.012]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere039.geometry}
        material={materials.skala}
        position={[19.543, 66.652, -47.866]}
        rotation={[-0.38, 1.194, 3.012]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere040.geometry}
        material={materials.skala}
        position={[12.633, 46.277, -41.08]}
        rotation={[-0.38, 1.194, 3.012]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere041.geometry}
        material={materials.yellow}
        position={[-6.194, 3.842, -54.029]}
        rotation={[0, -0.098, 0]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere042.geometry}
        material={materials.yellow}
        position={[-2.904, 3.842, -53.299]}
        rotation={[Math.PI, -1.245, Math.PI]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere043.geometry}
        material={materials.yellow}
        position={[-5.964, 3.842, -56.264]}
        rotation={[0, -0.486, 0]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere044.geometry}
        material={materials.yellow}
        position={[10.329, 3.842, -54.237]}
        rotation={[0, 0.364, 0]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere045.geometry}
        material={materials.yellow}
        position={[9.183, 3.842, -57.38]}
        rotation={[Math.PI, -0.404, Math.PI]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere046.geometry}
        material={materials.yellow}
        position={[0.716, 3.842, -52.69]}
        rotation={[-Math.PI, 0.698, -Math.PI]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere047.geometry}
        material={materials.yellow}
        position={[6.44, 3.842, -51.987]}
        rotation={[0, -0.461, 0]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere048.geometry}
        material={materials.yellow}
        position={[-1.223, 3.842, -50.793]}
        rotation={[0, -0.461, 0]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere049.geometry}
        material={materials.yellow}
        position={[-4.691, 3.842, -50.128]}
        rotation={[0, -0.029, 0]}
        scale={0.164}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere050.geometry}
        material={materials.yellow}
        position={[10.313, 3.842, -50.717]}
        rotation={[Math.PI, -1.191, Math.PI]}
        scale={0.164}
      />
    </group>
  );
}

useGLTF.preload("/waterfall.glb");
