/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Mesh;
  };
  materials: {
    [key: string]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/waterfall.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="mountain" position={[-0.606, 36.41, -51.459]}>
        <mesh
          name="Cube026"
          geometry={nodes.Cube026.geometry}
          material={materials.mud}
        />
        <mesh
          name="Cube026_1"
          geometry={nodes.Cube026_1.geometry}
          material={materials.grass}
        />
      </group>
      <mesh
        name="water"
        geometry={nodes.water.geometry}
        material={materials.water}
        position={[0.291, 40.4, -59.397]}
        rotation={[0, -0.026, 0]}
        scale={[16.355, 22.824, 31.278]}
      />
      <mesh
        name="water001"
        geometry={nodes.water001.geometry}
        material={materials.water}
        position={[56.082, 40.4, -57.509]}
        rotation={[0, -0.172, 0]}
        scale={[16.355, 22.824, 31.278]}
      />
      <mesh
        name="water002"
        geometry={nodes.water002.geometry}
        material={materials.water}
        position={[-53.966, 40.4, -57.098]}
        rotation={[0, 0.201, 0]}
        scale={[16.355, 22.824, 31.278]}
      />
      <group
        name="kufer"
        position={[3.753, 5.798, -55.787]}
        rotation={[-0.054, 0, 0.038]}
      >
        <mesh
          name="Cube027"
          geometry={nodes.Cube027.geometry}
          material={materials.tree}
        />
        <mesh
          name="Cube027_1"
          geometry={nodes.Cube027_1.geometry}
          material={materials.steel}
        />
        <mesh
          name="Cube027_2"
          geometry={nodes.Cube027_2.geometry}
          material={materials.yellow}
        />
      </group>
      <mesh
        name="Plane226"
        geometry={nodes.Plane226.geometry}
        material={materials.water}
        position={[0.918, -0.064, -5.311]}
        scale={[94.934, 91.285, 91.285]}
      />
      <group
        name="pinecones"
        position={[-0.136, 80.313, -67.982]}
        scale={[4.292, 2.878, 4.292]}
      >
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials["wystajaca trawa"]}
        />
        <mesh
          name="Cylinder001_1"
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.tree}
        />
      </group>
      <group
        name="island"
        position={[0.175, 2.327, 17.809]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-4.589, -0.421, -4.589]}
      >
        <mesh
          name="Cube005"
          geometry={nodes.Cube005.geometry}
          material={materials.mud}
        />
        <mesh
          name="Cube005_1"
          geometry={nodes.Cube005_1.geometry}
          material={materials.grass}
        />
      </group>
      <group
        name="sword_in_rock"
        position={[0.175, 7.208, 17.809]}
        scale={0.22}
      >
        <mesh
          name="Icosphere004"
          geometry={nodes.Icosphere004.geometry}
          material={materials.steel}
        />
        <mesh
          name="Icosphere004_1"
          geometry={nodes.Icosphere004_1.geometry}
          material={materials.sword_handle}
        />
        <mesh
          name="Icosphere004_2"
          geometry={nodes.Icosphere004_2.geometry}
          material={materials.rock}
        />
      </group>
      <group
        name="jump_block1"
        position={[1.504, 3.741, -11.422]}
        scale={3.275}
      >
        <mesh
          name="Cube025"
          geometry={nodes.Cube025.geometry}
          material={materials.rock}
        />
        <mesh
          name="Cube025_1"
          geometry={nodes.Cube025_1.geometry}
          material={materials.grass}
        />
      </group>
      <group
        name="jump_block2"
        position={[1.504, 3.741, -21.796]}
        scale={3.275}
      >
        <mesh
          name="Cube025"
          geometry={nodes.Cube025.geometry}
          material={materials.rock}
        />
        <mesh
          name="Cube025_1"
          geometry={nodes.Cube025_1.geometry}
          material={materials.grass}
        />
      </group>
      <group
        name="jump_block2001"
        position={[1.504, 3.741, -34.526]}
        scale={3.275}
      >
        <mesh
          name="Cube025"
          geometry={nodes.Cube025.geometry}
          material={materials.rock}
        />
        <mesh
          name="Cube025_1"
          geometry={nodes.Cube025_1.geometry}
          material={materials.grass}
        />
      </group>
      <mesh
        name="stone"
        geometry={nodes.stone.geometry}
        material={materials.rock}
        position={[17.801, 4.586, 7.41]}
        rotation={[-0.582, -0.07, 2.662]}
        scale={[0.603, 0.441, 0.411]}
      />
      <mesh
        name="boulder1"
        geometry={nodes.boulder1.geometry}
        material={materials.rock}
        position={[-6.604, 10.401, 9.288]}
        rotation={[2.465, 0.106, 1.854]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="boulder2"
        geometry={nodes.boulder2.geometry}
        material={materials.rock}
        position={[0.761, 6.064, 1.957]}
        rotation={[1.757, -0.566, 0.479]}
        scale={9.35}
      />
      <mesh
        name="boulder3"
        geometry={nodes.boulder3.geometry}
        material={materials.rock}
        position={[8.777, 6.959, 2.823]}
        rotation={[-2.778, -0.132, -2.532]}
        scale={7.384}
      />
      <mesh
        name="boulder4"
        geometry={nodes.boulder4.geometry}
        material={materials.rock}
        position={[-12.064, 6.698, 3.679]}
        rotation={[-1.113, -0.132, -2.532]}
        scale={6.482}
      />
      <group
        name="flower"
        position={[0.153, 4.809, 18.857]}
        rotation={[-3.121, -0.859, 2.974]}
        scale={[0.467, 0.441, 0.445]}
      >
        <mesh
          name="Plane013"
          geometry={nodes.Plane013.geometry}
          material={materials.tree}
        />
        <mesh
          name="Plane013_1"
          geometry={nodes.Plane013_1.geometry}
          material={materials.yellow}
        />
        <mesh
          name="Plane013_2"
          geometry={nodes.Plane013_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        name="pien"
        position={[11.371, 12.428, 19.219]}
        rotation={[0, -0.509, 0]}
      >
        <mesh
          name="Plane011"
          geometry={nodes.Plane011.geometry}
          material={materials.tree}
        />
        <mesh
          name="Plane011_1"
          geometry={nodes.Plane011_1.geometry}
          material={materials.grass}
        />
      </group>
      <group
        name="pien001"
        position={[-12.859, 12.428, 15.841]}
        rotation={[-Math.PI, 1.097, -Math.PI]}
      >
        <mesh
          name="Plane011"
          geometry={nodes.Plane011.geometry}
          material={materials.tree}
        />
        <mesh
          name="Plane011_1"
          geometry={nodes.Plane011_1.geometry}
          material={materials.grass}
        />
      </group>
      <group
        name="pien002"
        position={[13.341, 8.94, 29.614]}
        rotation={[0, -1.474, 0]}
        scale={0.582}
      >
        <mesh
          name="Plane011"
          geometry={nodes.Plane011.geometry}
          material={materials.tree}
        />
        <mesh
          name="Plane011_1"
          geometry={nodes.Plane011_1.geometry}
          material={materials.grass}
        />
      </group>
      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={materials["wystajaca trawa"]}
        position={[5.579, 4.682, 25.29]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.078, 0.907, 0.251]}
      />
      <mesh
        name="Icosphere016"
        geometry={nodes.Icosphere016.geometry}
        material={materials.rock}
        position={[24.934, 36.889, -38.878]}
        rotation={[-2.021, 0.117, 1.83]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere017"
        geometry={nodes.Icosphere017.geometry}
        material={materials.rock}
        position={[27.444, 39.721, -37.973]}
        rotation={[0.417, -0.915, -2.027]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere018"
        geometry={nodes.Icosphere018.geometry}
        material={materials.rock}
        position={[32.99, 31.911, -38.491]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere019"
        geometry={nodes.Icosphere019.geometry}
        material={materials.rock}
        position={[84.419, 67.128, -38.135]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere020"
        geometry={nodes.Icosphere020.geometry}
        material={materials.rock}
        position={[72.158, 10.499, -30.24]}
        rotation={[0.417, -0.915, -2.027]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere021"
        geometry={nodes.Icosphere021.geometry}
        material={materials.rock}
        position={[81.678, 47.164, -31.878]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere022"
        geometry={nodes.Icosphere022.geometry}
        material={materials.rock}
        position={[-29.211, 37.559, -35.169]}
        rotation={[1.516, -1.242, -1.15]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere023"
        geometry={nodes.Icosphere023.geometry}
        material={materials.rock}
        position={[-21.618, 53.476, -38.383]}
        rotation={[0.417, -0.915, -2.027]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere024"
        geometry={nodes.Icosphere024.geometry}
        material={materials.rock}
        position={[-15.26, 20.83, -36.514]}
        rotation={[-0.278, 0.08, 1.846]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere026"
        geometry={nodes.Icosphere026.geometry}
        material={materials.rock}
        position={[82.628, 72.05, -48.883]}
        rotation={[-1.94, 0.609, 1.34]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere027"
        geometry={nodes.Icosphere027.geometry}
        material={materials.rock}
        position={[91.237, 71.88, -65.527]}
        rotation={[-1.94, 0.609, 1.34]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere028"
        geometry={nodes.Icosphere028.geometry}
        material={materials.rock}
        position={[87.276, 74.451, -78.071]}
        rotation={[-1.995, 0.265, -2.726]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere029"
        geometry={nodes.Icosphere029.geometry}
        material={materials.rock}
        position={[89.739, 69.296, -46.087]}
        rotation={[-1.94, 0.609, 1.34]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere030"
        geometry={nodes.Icosphere030.geometry}
        material={materials.rock}
        position={[-85.088, 32.396, -59.658]}
        rotation={[1.757, -0.566, 0.479]}
        scale={9.35}
      />
      <mesh
        name="Icosphere031"
        geometry={nodes.Icosphere031.geometry}
        material={materials.rock}
        position={[-76.171, 64.949, -46.2]}
        rotation={[0.204, 1.01, 0.61]}
        scale={9.35}
      />
      <mesh
        name="Icosphere032"
        geometry={nodes.Icosphere032.geometry}
        material={materials.rock}
        position={[-84.602, 51.24, -28.994]}
        rotation={[-2.778, -0.132, -2.532]}
        scale={7.384}
      />
      <mesh
        name="Icosphere033"
        geometry={nodes.Icosphere033.geometry}
        material={materials.rock}
        position={[-67.125, 27.141, -30.22]}
        rotation={[1.003, -0.249, 1.08]}
        scale={7.384}
      />
      <mesh
        name="Icosphere034"
        geometry={nodes.Icosphere034.geometry}
        material={materials.rock}
        position={[-31.636, 73.038, -87.809]}
        rotation={[-1.113, -0.132, -2.532]}
        scale={6.482}
      />
      <mesh
        name="Icosphere035"
        geometry={nodes.Icosphere035.geometry}
        material={materials.rock}
        position={[-25.348, 68.748, -55.886]}
        rotation={[-2.394, -0.721, -1.102]}
        scale={6.482}
      />
      <mesh
        name="Icosphere036"
        geometry={nodes.Icosphere036.geometry}
        material={materials.rock}
        position={[32.99, 53.81, -39.474]}
        rotation={[0.683, 0.085, 1.87]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere037"
        geometry={nodes.Icosphere037.geometry}
        material={materials.rock}
        position={[27.568, 76.503, -82.498]}
        rotation={[-2.78, 1.431, -0.401]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere038"
        geometry={nodes.Icosphere038.geometry}
        material={materials.rock}
        position={[29.351, 72.911, -58.517]}
        rotation={[-0.38, 1.194, 3.012]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere039"
        geometry={nodes.Icosphere039.geometry}
        material={materials.rock}
        position={[23.344, 67.141, -50.105]}
        rotation={[-0.38, 1.194, 3.012]}
        scale={[8.278, 3.881, 4.51]}
      />
      <mesh
        name="Icosphere040"
        geometry={nodes.Icosphere040.geometry}
        material={materials.rock}
        position={[16.985, 46.765, -39.873]}
        rotation={[-0.38, 1.194, 3.012]}
        scale={[8.278, 3.881, 4.51]}
      />
    </group>
  );
}

useGLTF.preload("/waterfall.glb");
